### ISSUE TITLE
日志bug

### ISSUE THREAD

**Issue by DollyDino99** [fuguiKz/meituan-shenquan#1]
我是手动修改了文件把token以及推送key推送选项填入的，使用docker容器手动运行后无法输入选项选择 导致容器卡死 回看日志一分钟之内暴涨至2G 删除日志文件后才恢复正常 可否去除选择机制选择自行修改文件或变量机制呢？

**Comment by DollyDino99** [comment]
我是用的青龙容器运行的 如果大佬知道的话 不知道的话可以理解为一个js py容器 无法在脚本运行时输入sh命令

**Comment by DollyDino99** [comment]
我早上一看内存直接50g满了 大哥 你这日志输出到哪  我去删一下 服务器直接炸了

**Comment by fuguiKz** [comment]
docker容器正在试图支持，请注意此次北京时间早上10点20左右修复的 **输出文件路径异常** 理论与你自行构建的docker 导致内存爆满无关
具体内存爆满可能与docker 所要求的输出方式有关，请暂时直接使用实体机运行脚本，正试图构建docker支持，感谢反馈
